---
- name: Update package manager
  apt:
    update_cache: true
    upgrade: dist

- name: Remove unnecessary software
  apt:
    name: "{{ pckt }}"
    state: absent
  loop:
    - telnetd
    - ftpd
    - rsh-server
    - talk
    - talkd
    - xinetd
    - tftpd
  loop_control:
    loop_var: pckt

- name: Configure SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
      - "80"
      - "443"
      - "8081:8083"
    jump: ACCEPT

- name: Configure auditd
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^max_log_file"
    line: "max_log_file = 10"
  notify:
    - auditd_restart
