---
- name: Install LAMP Packages
  ansible.builtin.apt:
    name:
      [
        "apache2",
        "mysql-server",
        "python3-pymysql",
        "php",
        "php-mysql",
        "libapache2-mod-php",
      ]
    update_cache: true
    state: present

# Apache
- name: Create document root
  ansible.builtin.file:
    path: /var/www/{{ http_host }}
    state: directory
    owner: "{{ app_user }}"
    mode: 0755
  register: apache2_new_root

- name: Set up Apache virtualhost
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/{{ http_conf }}
    mode: 0644
  register: apache2_new_host
  notify: Reload Apache

- name: Enable new site
  ansible.builtin.command: /usr/sbin/a2ensite {{ http_conf }}
  when: "(apache2_new_root is changed) or (apache2_new_host is changed)"
  notify: Reload Apache

- name: Disable default Apache site
  ansible.builtin.command: /usr/sbin/a2dissite 000-default.conf
  changed_when: true
  when:
    - disable_default
    - (apache2_new_root is changed) or (apache2_new_host is changed)
  notify: Reload Apache

# MySQL Configuration
- name: Sets the root password
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ""
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

# UFW Configuration
- name: "UFW - Allow HTTP on port {{ http_port }}"
  community.general.ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

# PHP Info Page
- name: Sets Up PHP Info Page
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/{{ http_host }}/info.php
    mode: 0644
